/**
 * Images Defines
 * @author Passion UI <passionui.com>
 */

export const Images = {
  logo: require("@assets/images/logo.png"),
  banner1: require("@assets/images/slideshow1.jpg"),
  banner2: require("@assets/images/slideshow2.jpg"),
  banner3: require("@assets/images/slideshow3.jpg"),  
  cat1: require("@assets/images/cat1.png"),  
  cat2: require("@assets/images/cat2.png"),  
  cat3: require("@assets/images/cat3.png"),  
  cat4: require("@assets/images/cat4.png"),  
  cat5: require("@assets/images/cat5.png"),  
  cat6: require("@assets/images/cat6.png"),  
  cat7: require("@assets/images/cat7.png"),  
  cat8: require("@assets/images/cat8.png"),  

  slide: require("@assets/images/slide.png"),
  avata1: require("@assets/images/avata-01.jpeg"),
  avata2: require("@assets/images/avata-02.jpeg"),
  avata3: require("@assets/images/avata-03.jpeg"),
  avata4: require("@assets/images/avata-04.jpeg"),
  profile1: require("@assets/images/profile-1.jpg"),
  profile2: require("@assets/images/profile-2.jpg"),
  profile3: require("@assets/images/profile-3.jpg"),
  profile4: require("@assets/images/profile-4.jpg"),
  profile5: require("@assets/images/profile-5.jpg"),
  profile6: require("@assets/images/profile-6.jpg"),
  profile7: require("@assets/images/profile-7.jpg"),
  profile8: require("@assets/images/profile-8.jpg"),
  trip1: require("@assets/images/trip-1.jpg"),
  trip2: require("@assets/images/trip-2.jpg"),
  trip3: require("@assets/images/trip-3.jpg"),
  trip4: require("@assets/images/trip-4.jpg"),
  trip5: require("@assets/images/trip-5.jpg"),
  trip6: require("@assets/images/trip-6.jpg"),
  trip7: require("@assets/images/trip-7.jpg"),
  trip8: require("@assets/images/trip-8.jpg"),
  trip9: require("@assets/images/trip-9.jpg"),
  room1: require("@assets/images/room-1.jpg"),
  room2: require("@assets/images/room-2.jpg"),
  room3: require("@assets/images/room-3.jpg"),
  room4: require("@assets/images/room-4.jpg"),
  room5: require("@assets/images/room-5.jpg"),
  room6: require("@assets/images/room-6.jpg"),
  room7: require("@assets/images/room-7.jpg"),
  room8: require("@assets/images/room-8.jpg"),
  room9: require("@assets/images/room-9.jpg"),
  room10: require("@assets/images/room-10.jpg"),
  room11: require("@assets/images/room-11.jpg"),
  
  category1: require("@assets/images/category-1.jpg"),
  category2: require("@assets/images/category-2.jpg"),
  category3: require("@assets/images/category-3.jpg"),
  category4: require("@assets/images/category-4.jpg"),
  gallery1: require("@assets/images/gallery-1.jpg"),
  gallery2: require("@assets/images/gallery-2.jpg"),
  location1: require("@assets/images/location-1.jpg"),
  location2: require("@assets/images/location-2.jpg"),
  location3: require("@assets/images/location-3.jpg"),
  location4: require("@assets/images/location-4.jpg"),
  location5: require("@assets/images/location-5.jpg"),
  location6: require("@assets/images/location-6.jpg"),
  location7: require("@assets/images/location-7.jpg"),
  place1: require("@assets/images/place-1.jpg"),
  place2: require("@assets/images/place-2.jpg"),
  service1: require("@assets/images/service-shopping.jpg"),
  service2: require("@assets/images/service-automotive.jpg"),
  service3: require("@assets/images/service-coffee.jpg"),
  service4: require("@assets/images/service-event.jpg"),
  service5: require("@assets/images/service-housing.jpg"),
  service6: require("@assets/images/service-job.jpg"),
  service7: require("@assets/images/service-restaurant.jpg")
};
